### PR TITLE
Add code to parse beatmapset links, beatmap difficulty links and beat…

### PR DESCRIPTION
**Pull request by manav2511**
…map difficulty IDs to return list of beatmapset IDs

### CODE REVIEW

**Review by oblionC — COMMENTED** [review]
amazing code

**Comment by cya-n** [comment]
thank you

**Comment by Ram-eez** [comment]
nice code bro

**Comment by cya-n** [comment]
> nice code bro

https://www.youtube.com/watch?v=O08XTXJSOtI

**Pull request merged**
